export const demoPosts = [
  {
    id: 1,
    text: "Feeling really overwhelmed with schoolwork these days. It’s hard to balance everything.",
    upvotes: 12,
    tag: "School",
    mood: "Anxious",
    userName: "Aarav",
    comments: [
      {
        id: 101,
        text: "I get that, same here with assignments. You’ll get through it!",
        createdAt: Date.now() - 100000,
      },
      {
        id: 102,
        text: "Take it one step at a time 💪",
        createdAt: Date.now() - 90000,
      },
    ],
    createdAt: Date.now() - 200000,
    reported: false,
  },
  {
    id: 2,
    text: "Had a really good day with my family, feeling grateful.",
    upvotes: 25,
    tag: "Family",
    mood: "Happy",
    userName: "Ishita",
    comments: [
      {
        id: 103,
        text: "That’s so wholesome ❤️",
        createdAt: Date.now() - 80000,
      },
    ],
    createdAt: Date.now() - 180000,
    reported: false,
  },
  {
    id: 3,
    text: "Feeling lonely even when surrounded by friends. Weird vibe lately.",
    upvotes: 7,
    tag: "Friendship",
    mood: "Sad",
    userName: "Rohan",
    comments: [
      {
        id: 104,
        text: "You’re not alone, we all feel like this sometimes.",
        createdAt: Date.now() - 70000,
      },
      {
        id: 105,
        text: "Talk to them openly, maybe they don’t realize.",
        createdAt: Date.now() - 65000,
      },
    ],
    createdAt: Date.now() - 160000,
    reported: false,
  },
  {
    id: 4,
    text: "Stress is hitting hard before exams 😓",
    upvotes: 18,
    tag: "Stress",
    mood: "Anxious",
    userName: "Meera",
    comments: [
      {
        id: 106,
        text: "Same here! Let’s study together maybe?",
        createdAt: Date.now() - 60000,
      },
    ],
    createdAt: Date.now() - 140000,
    reported: false,
  },
  {
    id: 5,
    text: "Had an argument with a close friend. Don’t know how to fix it.",
    upvotes: 10,
    tag: "Friendship",
    mood: "Confused",
    userName: "Kabir",
    comments: [
      {
        id: 107,
        text: "Give them some space first, then talk calmly.",
        createdAt: Date.now() - 50000,
      },
      {
        id: 108,
        text: "I faced this too, honesty is the best way.",
        createdAt: Date.now() - 40000,
      },
    ],
    createdAt: Date.now() - 120000,
    reported: false,
  },
  {
    id: 6,
    text: "Some days I just don’t feel motivated to do anything.",
    upvotes: 15,
    tag: "General",
    mood: "Sad",
    userName: "Simran",
    comments: [
      {
        id: 109,
        text: "That’s okay, rest is also important.",
        createdAt: Date.now() - 35000,
      },
    ],
    createdAt: Date.now() - 100000,
    reported: false,
  },
  {
    id: 7,
    text: "Finally completed a tough project today! Feeling proud.",
    upvotes: 30,
    tag: "School",
    mood: "Happy",
    userName: "Aditya",
    comments: [
      { id: 110, text: "Congrats man! 🎉", createdAt: Date.now() - 32000 },
      { id: 111, text: "Hard work pays off 🙌", createdAt: Date.now() - 28000 },
    ],
    createdAt: Date.now() - 95000,
    reported: false,
  },
  {
    id: 8,
    text: "Getting really angry at small things lately. Not sure why.",
    upvotes: 6,
    tag: "General",
    mood: "Angry",
    userName: "Neha",
    comments: [
      {
        id: 112,
        text: "Maybe stress is triggering it? Try journaling.",
        createdAt: Date.now() - 25000,
      },
    ],
    createdAt: Date.now() - 85000,
    reported: false,
  },
  {
    id: 9,
    text: "Miss my old school friends. Things feel so different now.",
    upvotes: 9,
    tag: "Friendship",
    mood: "Sad",
    userName: "Ananya",
    comments: [
      {
        id: 113,
        text: "Same here, growing up sucks sometimes.",
        createdAt: Date.now() - 20000,
      },
    ],
    createdAt: Date.now() - 80000,
    reported: false,
  },
  {
    id: 10,
    text: "I don’t know what career I should pursue, feels confusing.",
    upvotes: 11,
    tag: "General",
    mood: "Confused",
    userName: "Harsh",
    comments: [
      {
        id: 114,
        text: "Talk to seniors or mentors, helps a lot.",
        createdAt: Date.now() - 18000,
      },
      {
        id: 115,
        text: "You’ll figure it out, don’t stress too much.",
        createdAt: Date.now() - 15000,
      },
    ],
    createdAt: Date.now() - 75000,
    reported: false,
  },
  {
    id: 11,
    text: "Had a peaceful walk this evening, nature really heals.",
    upvotes: 20,
    tag: "Stress",
    mood: "Neutral",
    userName: "Priya",
    comments: [
      {
        id: 116,
        text: "Walking outside clears my head too!",
        createdAt: Date.now() - 12000,
      },
    ],
    createdAt: Date.now() - 70000,
    reported: false,
  },
  {
    id: 12,
    text: "Got scolded by parents, feeling pretty down.",
    upvotes: 5,
    tag: "Family",
    mood: "Sad",
    userName: "Arjun",
    comments: [
      {
        id: 117,
        text: "They’ll cool down, don’t worry too much.",
        createdAt: Date.now() - 9000,
      },
    ],
    createdAt: Date.now() - 65000,
    reported: false,
  },
  {
    id: 13,
    text: "Made new friends today! They seem really nice.",
    upvotes: 22,
    tag: "Friendship",
    mood: "Happy",
    userName: "Tanya",
    comments: [
      {
        id: 118,
        text: "That’s awesome! Cherish the vibes ✨",
        createdAt: Date.now() - 6000,
      },
    ],
    createdAt: Date.now() - 60000,
    reported: false,
  },
  {
    id: 14,
    text: "Woke up feeling anxious without any reason.",
    upvotes: 8,
    tag: "Anxiety",
    mood: "Anxious",
    userName: "Rahul",
    comments: [
      {
        id: 119,
        text: "Happens with me too. Try breathing exercises.",
        createdAt: Date.now() - 4000,
      },
    ],
    createdAt: Date.now() - 55000,
    reported: false,
  },
  {
    id: 15,
    text: "Completed my to-do list today. Feels good to be productive!",
    upvotes: 16,
    tag: "General",
    mood: "Happy",
    userName: "Kavya",
    comments: [
      {
        id: 120,
        text: "That’s motivating me to do mine 😅",
        createdAt: Date.now() - 2000,
      },
    ],
    createdAt: Date.now() - 50000,
    reported: false,
  },
];
